name: github pages

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: wizhi/setup-buf@v1
        with:
          version: 0.51.0
      - name: Install Protoc
        uses: arduino/setup-protoc@master
        with:
          version: '3.18'

      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - run: go generate gen.go

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Github Actions
          author_email: klim0v-sergey@yandex.ru
          message: "generate files"
          add: "./api_pb"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push java
        uses: peaceiris/actions-gh-pages@v3.5.5
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: MinterTeam/node-grpc-java
          publish_branch: master
          publish_dir: ./gen/java
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
